services:
  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - /home/mysql/data:/var/lib/mysql
      - /home/mysql/conf.d:/etc/mysql/conf.d
      - /home/mysql/log:/var/log/mysql
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3306:3306"
    networks:
      - server_net
    environment:
      MYSQL_ROOT_PASSWORD: MySql密码

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - /home/redis/data:/data
      - /home/redis/redis.conf:/etc/redis/redis.conf
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "6379:6379"
    networks:
      - server_net
    command: ["redis-server", "/etc/redis/redis.conf"]

  minio:
    image: minio/minio:latest
    container_name: minio
    volumes:
      - /home/minio/data:/data
      - /home/minio/config:/root/.minio
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - server_net
    environment:
      MINIO_ROOT_USER: Minio用户名
      MINIO_ROOT_PASSWORD: Minio密码
      # 加上端口，url才会不显示端口
      MINIO_SERVER_URL: https://static.yshujia.cn:9000
      MINIO_BROWSER_REDIRECT_URL: https://static.yshujia.cn
      # --console-address=":9001"
    command: server /data --console-address=":9001"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - /home/nginx/https:/usr/share/nginx/https
      - /home/nginx/logs:/var/log/nginx
      - /home/nginx/html:/usr/share/nginx/html
      - /home/nginx/cache:/usr/share/html
      - /home/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - server_net

  java:
    build:
      context: /home/java
      dockerfile: /home/java/Dockerfile
    container_name: java
    volumes:
      - /home/java:/home/java
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9898:9898"
      - "9092:9092"
      - "587:587"
    networks:
      - server_net

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - /home/jenkins:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - server_net

networks:
  server_net:
    driver: bridge